### PR TITLE
Albert's change in readme

### PR DESCRIPTION
**Pull request by albertgab**

### CODE REVIEW

**Comment by BarathNallusamy** [comment]
Ready to pull

**Comment by DLewisSG** [comment]
Changes look good

**Review by DLewisSG — APPROVED** [review]

**Review by BarathNallusamy — APPROVED** [review]
Approved to make the change

**Review by mbeard88 — APPROVED** [review]
Barely OK

**Review by DLewisSG — CHANGES_REQUESTED** [review]
Change the content

**Review by DLewisSG — APPROVED** [review]
Much better

**Pull request merged**
